/**
 * Verifies a reCAPTCHA v2 token with the backend API.
 * @param {string} token - The token generated by the v2 widget.
 * @param {string} action - 'login' or 'register'
 * @returns {Promise<boolean>}
 */
export async function verifyRecaptcha(token, action = 'login') {
    if (!token) {
        throw new Error('Please complete the reCAPTCHA challenge.');
    }

    // Bypass backend verification if running locally in Vite (dev mode)
    // since Vercel serverless functions in /api/ don't run automatically with npm run dev
    if (import.meta.env.DEV) {
        console.warn(`[reCAPTCHA DEV BYPASS] Skipped backend verification for token.`);
        return true;
    }

    try {
        const res = await fetch('/api/verify-captcha', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ token, version: 'v2' })
        });

        const result = await res.json();

        if (!res.ok || !result.success) {
            const errorMsg = result.error || 'Security check failed. Please try again.';
            throw new Error(errorMsg);
        }

        console.log(`[reCAPTCHA v2 Verified] Action: ${action}`);
        return true;
    } catch (err) {
        console.error('[reCAPTCHA v2 Error]:', err);
        throw err;
    }
}
